version: "3.5"

services:
  orthanc:
    image: jodogne/orthanc-plugins:1.11.0
    hostname: orthanc
    volumes:
      # Config
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./db/:/var/lib/orthanc/db/
    ports:
      - "4242:4242" # DICOM
      - "8042:8042" # Web
    restart: unless-stopped
  orthanc-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
